### ISSUE TITLE
 "jsdoc/no-defaults": "off" ?

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eslint-config#59]
In old project we used to put the default in the jsDoc like:

https://github.com/cheminfo/spectra-processor/blob/994444c5259f748f0d76ba631f497673394a81ed/src/SpectraProcessor.js#L172-L174

and it appears like:

https://cheminfo.github.io/spectra-processor/#getpostprocesseddata

This is the case with JS projects and not TS or JS/TS projects.

I understand that there may be quickly a desync between code and documentation but it is a little bit hard to remove all the default values when we do `npm run eslint-fix`.

So I'm wondering if we should currently disable this rules or not.

**Comment by targos** [comment]
No objection to disable it for now
