### ISSUE TITLE
Add spaced-comment rule

### ISSUE THREAD

**Issue by stropitek** [cheminfo/eslint-config#69]
https://eslint.org/docs/latest/rules/spaced-comment

@cheminfo/collaborators can we add this rule as an error?

**Comment by stropitek** [comment]
I see that jsdoc comments get formatted differently than the way we are used to but I'd be ok with that.

**Comment by targos** [comment]
> This rule was deprecated in ESLint v8.53.0.

**Comment by tpoisseau** [comment]
SGTM to use https://eslint.style/rules/js/spaced-comment, 
Can you give us example on how it format differently than our existing jsdoc ?
