### ISSUE TITLE
ESLint couldn't find the config "eslint-config-cheminfo" to extend from. 

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eslint-config#8]
I tried to follow carefully the documentation in the project https://github.com/cheminfo-js/chromatography but since the package update it eslint fails:

```
chromatography [master] % npm run eslint-fix

> chromatography@3.12.0 eslint-fix /Users/lpatiny/git/cheminfo-js/chromatography
> npm run eslint -- --fix
```

```
Oops! Something went wrong! :(

ESLint: 6.6.0.

ESLint couldn't find the config "eslint-config-cheminfo" to extend from. Please check that the name of the config is correct.
```

I also don't understand why it searches for eslint-config-cheminfo while in the config file I entered `cheminfo`.

Actually I have the same problem in other projects as well.

**Comment by targos** [comment]
`eslint-config-cheminfo` is the full name of this package. The `eslint-config-` prefix can be omitted and ESLint will search automatically with the correct name.
I have no problem with the current state of https://github.com/cheminfo-js/chromatography
