### ISSUE TITLE
Is this warning required ?  prefer-named-capture-group

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eslint-config#9]
I'm used to write code like this one:
```
 let firstVariable = infos[0].replace(
              /.*\(([a-zA-Z0-9]+)\+\+.*/,
              '$1',
            );
```
But get the following warning
`99:15  warning  Capture group '([a-zA-Z0-9]+)' should be converted to a named or non-capturing group       prefer-named-capture-group`

And I'm not convinced that a named capture group would make the code more readable. I understand that if you have more than 2 capture groups it make sense but otherwise not.

I would suggest to remove this rule from our eslint-config as long as there is no way to specify that there should be over 2 capture groups to trigger the warning.

**Comment by targos** [comment]
This rule doesn't have options. 
We made it a warning so you can ignore it. 
If it's too annoying for you, you can always disable it project-wise or at the affected line.

**Comment by targos** [comment]
We added the rule specifically to remember us that named captures and non capturing groups exist and to exercise their usage.
